### ISSUE TITLE
Cli options -n --no-prompt not working

### ISSUE THREAD

**Issue by hexaltation** [frontity/docs#193]
Hello,
When passing the following command :
```
$ npx frontity create --no-prompt --theme @frontity/mars-theme myapp
```
or 
```
$ npx frontity create -n --theme @frontity/mars-theme myapp
```
I'm prompted back
```
? Do you want to receive framework updates by email? (y/N)
```
Am I misunderstanding `--no-prompt` option purpose ?
This blocks my automation for CI/CD cause it's waiting for an answer that will never come.

**Comment by mburridge** [comment]
@hexaltation Thanks for raising this. You're quite right `-n/--no-prompt` should mean that the command can be used in scripts that don't require any intervention on the part of the user. I've brought this to the attention of our dev team.

Feel free to raise the issue [here](https://github.com/frontity/frontity/issues) where it will be more visible to them. 

Alternatively, since Frontity is open source, feel free to create a PR with your own fix.

**Comment by juanmaguitar** [comment]
This seems to be a bug
https://github.com/frontity/frontity/issues/538
I close this issue as it will be managed by fixing the code
